server:
  port: 20080
  servlet:
    context-path: /sbp
spring:
  datasource:
    url: jdbc:h2:mem:sbp
    username: sa
    password:
    # execute sql when start
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  h2:
    console:
      # when spring-boot-devtools is in dependency, it's enabled by default
      enabled: true
  messages:
    basename: i18n.messages
    encoding: UTF-8
logging:
  level:
    app.lyd.springbootproject.app.dao.mapper: debug
spb:
  ws:
    endpoints: spb-ws
    simple-brokers: /topic
    destinations: /app
    enable-cors: true
    name-key: userId
    heartbeat:
      enable: true
      pool-size: 10
      period: 10000
